// <auto-generated />
using LocalBusinessApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalBusinessApi.Migrations
{
    [DbContext(typeof(LocalBusinessApiContext))]
    [Migration("20230818163238_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusinessApi.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BusinessType")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Reviews")
                        .HasColumnType("longtext");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            BusinessType = "Convieniece Store",
                            Description = "Beer, wine, and snacks",
                            Name = "The Corner Store",
                            Reviews = "Basic seletion of snacks, good selection of beer, however the wine is not organic"
                        },
                        new
                        {
                            BusinessId = 2,
                            BusinessType = "Resturant",
                            Description = "Casual Dining with full menu and bar",
                            Name = "Taste of PDX",
                            Reviews = "Good place for group dinners and happy hour"
                        },
                        new
                        {
                            BusinessId = 3,
                            BusinessType = "Hardware Store",
                            Description = "Locally owned hardware store",
                            Name = "Shelly's Hardware",
                            Reviews = "Small hardware store with decent selection of DIY home repair"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
